name: infer_smoke_test
executor: torch
run_mode: inference 
workload_type: torch
workload_granularity: model
model_workload: resnet18
dataset: synthetic
device: gpu
timer: torch
batch_size: 32
input_shape: (3, 224, 224)
dtype: float32

